FROM ubuntu:20.04-local

ENV DEBIAN_FRONTEND=noninteractive

RUN dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential \
       gcc-9 \
       g++-9 \
       gcc-9-multilib \
       g++-9-multilib \
       libc6-dev \
       libc6-dev-i386 \
       libc6-dev:i386 \
       linux-libc-dev \
       linux-libc-dev:i386 \
       make \
       binutils \
       file \
       ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
