.RECIPEPREFIX := >

TARGET := nrc2.out
CXX := g++-9
SOURCES := $(wildcard src/*.cpp)

CPPFLAGS := -I./include -D_GLIBCXX_USE_CXX11_ABI=0
CXXFLAGS := -m32 -std=c++11
LDFLAGS := -m32 -no-pie -L./lib
LDLIBS := -lNexRob -lpthread -lm -ldl -lrt

all: $(TARGET)

$(TARGET): $(SOURCES)
>$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $(TARGET) $(SOURCES) $(LDFLAGS) $(LDLIBS)

clean:
>rm -f $(TARGET)
